[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

[alias]
package-linux = "run --bin tbx-package -- linux"
package-windows = "run --bin tbx-package -- windows"
package-all = "run --bin tbx-package -- all"
