[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

[alias]
package-linux = "!scripts/package-linux.sh"
package-windows = "!scripts/package-windows.sh"
package-all = "!scripts/package-all.sh"
